### PR TITLE
Replace comma with space to fix search with point

### PR DESCRIPTION
**Pull request by benboughton1**

### CODE REVIEW

**Comment by olivierhagolle** [comment]
Dear Ben, 
thanks for the contribution, However, I am not sure, for two reasons :  

This example works :
 python  Sentinel_download.py --lat 43.6 --lon 1.44 -a apihub.txt -

And [the manual](https://scihub.copernicus.eu/userguide/5APIsAndBatchScripting) says the comma is necessary : 
POINT:
<geographic type>= Lat, Lon
where the Latitude ( Lat ) and Longitude ( Lon ) values are expressed in decimal degrees (DDD) format (e.g. 41.40338, 2.17403 ).
Example:
https://scihub.copernicus.eu/dhus/search?q=footprint:"Intersects(41.9000, 12.5000)"


What makes you think it is different ?
Best regards,
Olivier

**Comment by benboughton1** [comment]
The code was not working for me.

E.g. it would search this which would give 500 error:

https://scihub.copernicus.eu/apihub/search?q=footprint:%22Intersects(145.218046,-36.473107)%22%20filename:S2*%20ingestiondate:[2015-12-01T00:00:00.000Z%20TO%202015-12-31T23:59:50.000Z]

whereas this search URL works:

https://scihub.copernicus.eu/apihub/search?q=footprint:%22Intersects(145.218046%20-36.473107)%22%20filename:S2*%20ingestiondate:[2015-12-01T00:00:00.000Z%20TO%202015-12-31T23:59:50.000Z]

**Comment by olivierhagolle** [comment]
I have tried this : 
https://scihub.copernicus.eu/apihub/search?q=footprint:%22Intersects(43.6,1.44)%22%20filename:S2*%20ingestiondate:[2015-12-01T00:00:00.000Z%20TO%202015-12-31T23:59:50.000Z]

and it provides the following products which are the ones I need : 
<title>S2A_OPER_PRD_MSIL1C_PDMC_20151230T202002_R008_V20151230T105153_20151230T105153</title>
<title>S2A_OPER_PRD_MSIL1C_PDMC_20151226T193836_R094_V20151226T111142_20151226T111142</title>

While when I search 
https://scihub.copernicus.eu/apihub/search?q=footprint:%22Intersects(43.6%201.44)%22%20filename:S2*%20ingestiondate:[2015-12-01T00:00:00.000Z%20TO%202015-12-31T23:59:50.000Z]

I get other ones, which are not the ones I need.
<title>S2A_OPER_PRD_MSIL1C_PDMC_20151230T163525_R006_V20151230T073929_20151230T073929</title>
<title>S2A_OPER_PRD_MSIL1C_PDMC_20151230T143353_R006_V20151230T074743_20151230T074743</title>

There is something strange on the scihub server side... You should try to contact a helpdesk. For instance, eohelp@esa.int

Best regards,
Olivier

**Comment by olivierhagolle** [comment]
Hey, I guess I found out. 
you have interverted lon and lat.

It seems that with the comma,  it queries with lat,lon, while with the space it queries with lon lat

As a latitude of 146 is not possible, it gives an internal error.

Olivier

**Comment by benboughton1** [comment]
Thanks heaps


Sent from Outlook Mobile






On Fri, Jan 22, 2016 at 12:58 AM -0800, "olivierhagolle" <notifications@github.com> wrote:












Hey, I guess I found out. 

you have interverted lon and lat.



It seems that with the comma,  it queries with lat,lon, while with the space it queries with lon lat



As a latitude of 146 is not possible, it gives an internal error.



Olivier

**Pull request closed without merging**
